# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13eS338d1eshH6LElqt2l79ZSHBfIBsyj
"""

import numpy as np
import matplotlib.pyplot as plt

# Assuming your CSV file has two columns: Date and Price
# Replace 'your_stock_data.csv' with the actual file name
data = np.genfromtxt('AMZN.csv', delimiter=',', dtype=None, names=True)

# Extracting Dates and Prices
dates = data['Date']
prices = data['Open']

# Create a figure and axis
plt.figure(figsize=(10, 5))

# Plotting the data
plt.plot(dates, prices, label='Stock Price', color='blue')

# Adding labels and title
plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Stock Price Plot')

# Rotating x-axis labels for better visibility
plt.xticks(rotation=45)

# Adding legend
plt.legend()

# Show the plot
plt.show()

import matplotlib.pyplot as plt
from matplotlib.dates import date2num
import numpy as np

# Assuming your CSV file has four columns: Date, Open, High, Low, Close
# Replace 'your_stock_data.csv' with the actual file name
data = np.genfromtxt('AMZN.csv', delimiter=',', dtype=None, names=True)

# Extracting Dates, Open, High, Low, and Close
dates = data['Date']
opens = data['Open']
highs = data['High']
lows = data['Low']
closes = data['Close']

# Convert dates to matplotlib dates
dates = date2num(dates)

# Create a figure and axis
fig, ax = plt.subplots(figsize=(10, 5))

# Plotting candlesticks
for i in range(len(dates)):
    ax.plot([dates[i], dates[i]], [opens[i], closes[i]], color='black', linewidth=2)
    ax.plot([dates[i], dates[i]], [highs[i], lows[i]], color='red', linewidth=1)
    ax.plot([dates[i], dates[i]],[opens[i], closes[i]], color='green', linewidth=1)

# Set x-axis labels as dates
ax.xaxis_date()

# Setting labels and title
plt.xlabel('Date')
plt.ylabel('Price')
plt.title('Candlestick Chart')

# Rotating x-axis labels for better visibility
plt.xticks(rotation=45)

# Show the pl

import matplotlib.pyplot as plt
import numpy as np

# Assuming your CSV file has two columns: Date and Price
# Replace 'your_stock_data.csv' with the actual file name
data = np.genfromtxt('AMZN.csv', delimiter=',', dtype=None, names=True)

# Extracting Prices
prices = data['Open']

# Define the window size for the moving average
window_size = 2 # Adjust as needed

# Calculate the simple moving average
def calculate_sma(data, window_size):
    sma = np.cumsum(data, dtype=float)
    sma[window_size:] = sma[window_size:] - sma[:-window_size]
    return sma[window_size - 1:] / window_size

sma = calculate_sma(prices, window_size)

# Create a figure and axis
plt.figure(figsize=(10, 5))

# Plotting the original data
plt.plot(prices, label='Stock Price', color='blue')

# Plotting the moving average
plt.plot(range(window_size - 1, len(prices)), sma, label=f'SMA ({window_size} days)', color='red')

# Adding labels and title
plt.xlabel('Days')
plt.ylabel('Price')
plt.title('Stock Price with Moving Average')

# Adding legend
plt.legend()

# Show the plot
plt.show()
